# Generated by Django 4.1.1 on 2022-10-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('symbol', models.CharField(max_length=4, verbose_name='Simbolo')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Moficación')),
            ],
            options={
                'verbose_name': 'Moneda',
                'db_table': 'currency',
            },
        ),
    ]
