# Generated by Django 4.1.1 on 2022-10-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_productcategory_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
